package com.bankjatim.jims.security;

public enum UserRole {
    SUPER_ADMIN,
    USER_ADMIN,
    MASTER_MAKER,
    MASTER_APPROVER,
    BUDGET_OFFICER,
    PROCUREMENT_OFFICER,
    PROCUREMENT_APPROVER,
    INVENTORY_OFFICER,
    WAREHOUSE_OFFICER,
    REQUESTER_CABANG,
    ORDER_APPROVER,
    SWITCHING_APPROVER,
    DISTRIBUTION_OFFICER,
    RECEIVING_OFFICER,
    FINANCE_OFFICER,
    FINANCE_APPROVER,
    AUDITOR,
    MANAGEMENT
}
